app_name: RAG-Evals
version: 1.0.0
experiment_name: Rag_Evaluation_Experiment
evaluation:
  run_local: False
  input_path: src/evaluations/offline/rag_evaluation/datasets/
  input_file: rag_sample.jsonl
  output_path: src/evaluations/offline/rag_evaluation/report/
  column_mapping:
    user_id: "${data.query}"
  evaluators:
    relevance_score: "relevance_evaluator"
  evaluator_config:
    relevance_score:
      column_mapping:
        query: "${data.query}"
        response: "${data.response}" 
pipeline:
  - base_path: evaluator
    module: eval_main.eval_main
    config_key: evaluation
